notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
  email: false

language: python
cache: pip
python:
  - "3.8"
node_js:
  - 12

services:
  - mysql

install:
  - node -v
  - pip install poetry
  - poetry install

jobs:
  include:
    - stage: lint
      script:
        - poetry run black --check .
        - poetry run flake8 .
    - stage: test
      script:
        - mysql -e 'create database dhp;'
        - poetry run python manage.py migrate
        - npm ci
        - npm run build
        - poetry run pytest --cov
