language: python
python:
  - "3.4"
  - "3.5"
script:
  - python manage.py test --noinput
before_script:
  - gem install sass
  - mysql -e 'create database dhp;'
  - python manage.py migrate
  - npm install
  - sass assets/css/site.sass assets/css/site.css
  - python manage.py collectstatic --noinput --ignore *.sass
notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
