language: python
python:
  - "3.6"
services:
  - mysql
script:
  - poetry run pytest --cov
install:
  - pip install poetry
  - poetry install --dev
before_script:
  - mysql -e 'create database dhp;'
  - poetry run python manage.py migrate
  - npm ci
  - npm run build
services:
  - mysql
notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
  email: false
