notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
  email: false

language: python
cache: pip
python:
  - "3.6"

services:
  - mysql

stages:
  - lint
  - test

# Testing stage
install:
  - pip install poetry
  - poetry install
before_script:
  - mysql -e 'create database dhp;'
  - poetry run python manage.py migrate
  - npm ci
  - npm run build
script:
  - poetry run pytest --cov

# Other stages
jobs:
  include:
    - stage: lint
      script:
        - poetry run black --check .
        - poetry run flake8 .
