language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - python manage.py test --noinput
install:
  - pip install -r dev-requirements.txt
before_script:
  - mysql -e 'create database dhp;'
  - python manage.py migrate
  - npm install
  - bundle install
  - compass compile -e production
  - python manage.py collectstatic --noinput --ignore *.sass
notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
  email: false
