language: python
cache: pip
python:
  - "3.4"
  - "3.5"
script:
  - python manage.py test --noinput
install:
  - pip install -r dev-requirements.txt
before_script:
  - mysql -e 'create database dhp;'
  - python manage.py migrate
  - npm install
  - sass assets/css/site.sass assets/css/site.css
  - python manage.py collectstatic --noinput --ignore *.sass
notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
