language: python
python:
  - "3.6"
script:
  - pipenv run coverage run --source='.' manage.py test --noinput && coverage report
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - mysql -e 'create database dhp;'
  - pipenv run python manage.py migrate
  - npm install
  - npm run build
services:
  - mysql
notifications:
  slack: danehillard:ALNjxErNTEvNklCPFUNTw4Dz
  email: false
