# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_remove_photograph_uuid'),
        ('blog', '0003_auto_20151127_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_in', to='photography.Photograph'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_in', to='photography.Photograph'),
        ),
    ]
