# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20160119_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="go_live_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date and time to publish this post"),
        ),
    ]
