# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="photograph", options={},),
        migrations.RemoveField(model_name="photograph", name="public",),
        migrations.RemoveField(model_name="photograph", name="published_date",),
        migrations.RemoveField(model_name="photograph", name="user",),
    ]
