# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0003_auto_20160117_1424"),
    ]

    operations = [
        migrations.RemoveField(model_name="photograph", name="thumbnail_square",),
    ]
