# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0004_remove_photograph_thumbnail_square"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="filename",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
