# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_photograph_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
