# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0006_auto_20160118_2040"),
    ]

    operations = [
        migrations.RemoveField(model_name="photograph", name="uuid",),
    ]
