# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_remove_photograph_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='in_portfolio',
            field=models.BooleanField(default=False),
        ),
    ]
