# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0008_photograph_in_portfolio"),
    ]

    operations = [
        migrations.RemoveField(model_name="photograph", name="sq_height",),
        migrations.RemoveField(model_name="photograph", name="sq_width",),
    ]
